# Generated by Django 4.1 on 2022-11-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_restaurants_delete_myapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='menu',
            field=models.TextField(default=1, verbose_name='メニュー'),
            preserve_default=False,
        ),
    ]
