# Generated by Django 4.1 on 2023-01-17 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_menu_restaurants_access_restaurants_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='consideration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FootPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=-32400)),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='restaurants',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='category',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='カテゴリー'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='dinnerPrice',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='ディナー料金'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='lunchPrice',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='ランチ料金'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='map',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='地図'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='画像'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='place',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='地域'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.restaurants', verbose_name='レストラン'),
        ),
        migrations.DeleteModel(
            name='Myapp',
        ),
        migrations.AddField(
            model_name='like',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.restaurants'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='footprint',
            name='dst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst_footprint', to='myapp.restaurants'),
        ),
        migrations.AddField(
            model_name='footprint',
            name='src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_footprint', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consideration',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.restaurants'),
        ),
        migrations.AddField(
            model_name='consideration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
