# Generated by Django 4.1 on 2023-01-18 03:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0005_alter_restaurants_map'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('restaurant_id', 'user', 'restaurant_name')},
        ),
    ]
