# Generated by Django 4.1 on 2023-01-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='dinnerPrice',
            field=models.IntegerField(verbose_name='ディナー料金'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='lunchPrice',
            field=models.IntegerField(verbose_name='ランチ料金'),
        ),
    ]
