# Generated by Django 4.1 on 2023-01-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_restaurants_dinnerprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='photo',
            field=models.URLField(verbose_name='画像'),
        ),
    ]
