# Generated by Django 4.1 on 2023-01-22 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_restaurants_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='photo',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='画像'),
            preserve_default=False,
        ),
    ]
