# Generated by Django 4.1 on 2023-01-23 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_menu_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FootPrint',
        ),
    ]
