# Generated by Django 4.1 on 2023-02-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_footprint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='target',
            new_name='restaurant',
        ),
    ]
